[versions]
agp = "8.3.1"
junit = "4.13.2"
androidx-test-ext-junit = "1.1.5"
espresso-core = "3.5.1"
ftc-sdk = "11.0.0"
pedro-pathing = "2.0.0"

[libraries]
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-test-ext-junit" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso-core" }
ftc-robotcore = { group = "org.firstinspires.ftc", name = "RobotCore", version.ref = "ftc-sdk" }
ftc-hardware = { group = "org.firstinspires.ftc", name = "Hardware", version.ref = "ftc-sdk" }
ftc-robotserver = { group = "org.firstinspires.ftc", name = "RobotServer", version.ref = "ftc-sdk" }
ftc-common = { group = "org.firstinspires.ftc", name = "FtcCommon", version.ref = "ftc-sdk" }
ftc-onbotjava = { group = "org.firstinspires.ftc", name = "OnBotJava", version.ref = "ftc-sdk" }
ftc-inspection = { group = "org.firstinspires.ftc", name = "Inspection", version.ref = "ftc-sdk" }
pedro-pathing = { group = "com.github.Pedro-Pathing.PedroPathing", name = "ftc", version.ref = "pedro-pathing" }

[plugins]
androidLibrary = { id = "com.android.library", version.ref = "agp" }
